### ISSUE TITLE
WiFi&Bluetooth

### ISSUE THREAD

**Issue by sharky-j7** [pierrecle/Hackintosh-NUC9I7QNX-OpenCore#3]
You just need to update WiFi kext to 1.3 https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0
![speedtest](https://user-images.githubusercontent.com/84475963/118879744-c10aa580-b8f9-11eb-97e3-f04296ff658a.png)
With same Logitech devices I had same problems, still not resolved....

**Comment by bemble** [comment]
Yes, I finally took the time to update all kexts, including wifi. Indeed it's a lot better (theoric speed move from 147Mb/s to 300Mb/s), but it steel use `n` protocol and not `ac`. I updated the test speed and wifi information.
Thanks!
