### ISSUE TITLE
Is there any installation guides on this

### ISSUE THREAD

**Issue by Zekcode** [pierrecle/Hackintosh-NUC9I7QNX-OpenCore#4]
Hello :)

Great project, im looking for updateing my old Nuc (HaCmini project) for the intel nuc i9 series. i allready got the machine.

im confused, how do i install this? how do i mod the vanilla file?

can you help me?

Kind regards

**Comment by bemble** [comment]
Hi! Thanks for your message.

Take a look on [the OpenCore official guide](https://dortania.github.io/OpenCore-Install-Guide/), everything is here and the guide is better than what I could say.

Files and information I provide let you save some time on drivers and configuration. But these files/configurations are tested on the NUC9I7QNX serie, it might not work on your nuc if hardware is different. I used [HaCmini Guide](https://osy.gitbook.io/hac-mini-guide/), it should also be an important ressource for you.
