### ISSUE TITLE
Update to Big Sur 11.6

### ISSUE THREAD

**Issue by reketeee** [pierrecle/Hackintosh-NUC9I7QNX-OpenCore#5]
Hi :)
Thank you for share those files, i could manage to install and enjoy (after a long trial/error) a working hackintosh.
I'm trying to get working 11.6 update but i can't boot system. Will you update your files to make them compatible with 11.6?

Thank again!

**Comment by bemble** [comment]
Hi, thanks for your comment.

I will upgrade drivers in october I think, but I probably won't upgrade to Mac OS 11.6, my hackintosh works great on 11.4, it's stable and I use it everyday, I don't want to break my install for that kind of upgrade. That's also the reason why I don't upgrade Lilu, last time I did it I lost my USB configuration, it took me days to get it back, to find any information about the subject etc.

I think that's the reason why there is not a lot of hackintosh with the latest Mac OS version: when you have something stable, you don't take the risk to break all just for a fancy update.

To get back on your problem, if Mac OS doesn't boot on 11.6, it's probably a problem with Lilu and its configuration. Try to boot in debug and see what's displayed while trying to boot.

**Comment by reketeee** [comment]
Hi :)
Maybe is related to my system but i noticed (after trial/error) that if connect top ethernet system become unstable and hangs randomly.  I did a new clean install (11.2.3) and upgrade directly to 11.6 (using other ethernet port), after a few reboots, system boots correctly but without working USB ports.

Disabling USBInjectAll kext in your config.plist did the trick and mouse/keyboard worked again. System appears stable, hardware decode/enc works with a little changes in config.plist, DRM stuff too but ramdonly USB 3.0 devices like external disk aren't detected. What is really strange is that usb 2.0 disks works without any issues on any port. Also bluetooth appears is working (can enable/disable) but doesn't detect any devices. 

Should i upgrade OpenCore and all kext? 

Thanks again!
